#!/bin/sh

# This should be run on a fresh installation of Ubuntu 12.04 64-bit.
sudo apt-get update
sudo apt-get install python-lxml tesseract-ocr tesseract-ocr-eng coffeescript

# Serve port 8080 as port 80
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
# iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080

