#!/bin/sh

# This should be run on a fresh installation of Ubuntu 12.04 64-bit.

# The latest node
# https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manage
sudo apt-get install python-software-properties python g++ make
sudo add-apt-repository ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get install nodejs npm

# Other stuff
sudo apt-get install python-lxml tesseract-ocr tesseract-ocr-eng \
  coffeescript git

# Serve port 8080 as port 80
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
# iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080

cd /home/tlevine
git clone git@github.com:tlevine/scott.git --recursive
cd scott

(
  cd reader
  sudo pip install -r requirements.txt
)
(
  cd server
  npm install
)
