#!/bin/sh
set -e

# Compile the client
(
  cd client/js
  browserify -t brfs index.js > ../compiled.js
)

# Serve the website
(
  cd server

  # Such a hack
  while true; do
    coffee app.coffee
    sleep 2s
  done
)
