define([], function () {
  return [
    ['acadia', 'Acadia'],
    ['allen', 'Allen'],
    ['ascension', 'Ascension'],
    ['assumption', 'Assumption'],
    ['avoyelles', 'Avoyelles'],
    ['beauregard', 'Beauregard'],
    ['bienville', 'Bienville'],
    ['bossier', 'Bossier'],
    ['caddo', 'Caddo'],
    ['calcasieu', 'Calcasieu'],
    ['caldwell', 'Caldwell'],
    ['cameron', 'Cameron'],
    ['catahoula', 'Catahoula'],
    ['claiborne', 'Claiborne'],
    ['concordia', 'Concordia'],
    ['de soto', 'De Soto'],
    ['east baton Rouge', 'East Baton Rouge'],
    ['east carroll', 'East Carroll'],
    ['east feliciana', 'East Feliciana'],
    ['evangeline', 'Evangeline'],
    ['franklin', 'Franklin'],
    ['grant', 'Grant'],
    ['iberia', 'Iberia'],
    ['iberville', 'Iberville'],
    ['jackson', 'Jackson'],
    ['jefferson', 'Jefferson'],
    ['jefferson Davis', 'Jefferson Davis'],
    ['lafayette', 'Lafayette'],
    ['lafourche', 'Lafourche'],
    ['la salle', 'La Salle'],
    ['lincoln', 'Lincoln'],
    ['livingston', 'Livingston'],
    ['madison', 'Madison'],
    ['morehouse', 'Morehouse'],
    ['natchitoches', 'Natchitoches'],
    ['orleans', 'Orleans'],
    ['ouachita', 'Ouachita'],
    ['plaquemines', 'Plaquemines'],
    ['pointe Coupee', 'Pointe Coupee'],
    ['rapides', 'Rapides'],
    ['red river', 'Red River'],
    ['richland', 'Richland'],
    ['sabine', 'Sabine'],
    ['saint bernard', 'Saint Bernard'],
    ['saint charles', 'Saint Charles'],
    ['saint helena', 'Saint Helena'],
    ['saint james', 'Saint James'],
    ['saint john the baptist', 'Saint John the Baptist'],
    ['saint landry', 'Saint Landry'],
    ['saint martin', 'Saint Martin'],
    ['saint mary', 'Saint Mary'],
    ['saint tammany', 'Saint Tammany'],
    ['tangipahoa', 'Tangipahoa'],
    ['tensas', 'Tensas'],
    ['terrebonne', 'Terrebonne'],
    ['union', 'Union'],
    ['vermilion', 'Vermilion'],
    ['vernon', 'Vernon'],
    ['washington', 'Washington'],
    ['webster', 'Webster'],
    ['west baton Rouge', 'West Baton Rouge'],
    ['west carroll', 'West Carroll'],
    ['west feliciana', 'West Feliciana'],
    ['winn', 'Winn']
  ]
})
